# Generated by Django 4.2.6 on 2023-11-06 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_rename_title_tag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tag",
            new_name="tags",
        ),
    ]
