# Generated by Django 4.2.6 on 2023-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_tag_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="project.jpg", null=True, upload_to=""
            ),
        ),
    ]
